---
- name: Template test
  hosts: all
  user: devops
  become: true
  vars:
    system_owner: jjy@example.com
  tasks:
    - template:
        src: template/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
