---
- name: ensure httpd is installed
  yum:
    name: httpd
    state: latest

- name: ensure httpd is started ans enabled
  service:
    name: httpd
    state: started
    enabled: true

- name: vhost file is installed
  template:
    src: templates/vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd

- name: html content is installed
  copy:
    src: html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

