---
- name: Installing MariaDB server
  hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - MySQL-python
    db_service: mariadb
    resources_url: http://materials.example.com/labs/control-handlers
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf

  tasks:
    - name: "{{ db_packages }} packages are installed"
      yum:
        name: "{{ item }}"
        state: present 
      loop: "{{ db_packages }}"
      notify:
        - set db password

    - name: make sure the database service is running
      service:
        name: "{{ db_service }}"
        state: started
        enabled: true

    - name: "the {{ config_file_url }} file has been installed"
      get_url:
        url: "{{ config_file_url }}"
        dest: "{{ config_file_dst }}"
        owner: mysql
        group: mysql
        force: yes
      notify:
        - restart db service

  handlers:
    - name: restart db service
      service:
        name: "{{ db_service }}"
        state: restarted

    - name: set db password
      mysql_user:
        name: root
        password: redhat



