---
- name: Configure web server
  hosts: all

  tasks:
    - name: import the environment task file ans set the variables
      import_tasks: tasks/environment.yml
      vars:
        package: httpd
        service: httpd
    
    - name: import the firewall task file and set the variables
      import_tasks: tasks/firewall.yml
      vars:
        firewall_pkg: firewalld
        firewall_svc: firewalld
        rule: http

    - name: import the placeholder task file and set the variable
      import_tasks: tasks/placeholder.yml
      vars:
        file: /var/www/html/index.html

- name: Import test play file and set the variable
  import_playbook: plays/test.yml
  vars:
    url: 'http://servera.lab.example.com'
