---
- name: Task failure exercise
  hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb

  tasks:
    - name: check local time
      command: date
      register: res
      changed_when: false

    - name: print local time
      debug:
        var: res.stdout

    - block:
      - name: "install {{ web_package }} package"
        yum:
          name: "{{ web_package }}"
          state: present
        failed_when: web_package == "httpd"
#        ignore_errors: yes

      rescue:
        - name: "install {{ db_package }} package"
          yum:
            name: "{{ db_package }}"
            state: present
      
      always:
        - name: "start {{ db_service }} service"
          service:
            name: "{{ db_service }}"
            state: started
