---
- name: create user account for all our servers
  hosts: devservers
  remote_user: devops
  become: yes
  vars_files:
    - secret.yml
  
  tasks:
    - name: creating user from secret.yml
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"
