---
- name: Simple boolean task demo
  hosts: all 
  vars:
    run_my_task: true

  tasks:
    - name: httpd package is installed
      yum:
        name: httpd
        state: absent
      when: run_my_task
